ini_open('main.ini')
ini_write_real('main','ul',main.ul);
ini_write_real('main','day',main.day)
ini_close()
sgame()
main.alarm[4]=5
/*main.zy=ocr()
main.valn=1
with(pol){
alarm[0]=-1
plant=ocr()
}
instance_create(128,160,object6)
with(pul){
instance_destroy()
}
ini_open('main.ini')
ul=ini_write_real('main','ul',main.ul);
ini_close()
main.sn=75
main.alarm[1]=-1
main.alarm[3]=-1
